name: electron

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.x
      - name: Install dependencies
        run: |
          cd web && bun install
      - name: Build binary
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go build-electron
      - name: Build Electron (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd web
          export NODE_OPTIONS=--openssl-legacy-provider
          bun run build-electron
          bun electron-builder --mac -p never
      - name: Build Electron (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd web
          export NODE_OPTIONS=--openssl-legacy-provider
          bun run build-electron
          bun electron-builder --linux -p never
      - name: Build Electron (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd web
          set NODE_OPTIONS=--openssl-legacy-provider
          bun run build-electron
          bun electron-builder --win -p never
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: web/release
