name: preflight-checks
on: [push, pull_request]
# on:
#   push:
#     tags:
#     - 'v*'
#     branches:
#     - master
#     - release-*
#   pull_request:
#     branches:
#     - master
#     - release-*

jobs:
  go_unit_tests:
    strategy:
      matrix:
        go-version:
          - 1.17.x
        platform: [ubuntu-latest, macos-latest]
        # platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Golang tests on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: install_prettier
        run: |
          bun add -g prettier
      - name: run_go_tests
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go test

  verify_tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v4
      - name: Get tag
        run: echo "GITHUB_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Verify tag
        run: |
          bash ./ci/github-actions-tag-check.sh
        shell: bash

  node_unit_tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        # platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Karma tests on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.x
      - name: Install dependencies
        run: |
          cd web && bun install
      - name: run_karma
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          go run build.go web-test

  bundle_assets:
    needs: [go_unit_tests, node_unit_tests]
    strategy:
      matrix:
        go-version:
          - 1.17.x
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    name: Build on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          cd web && bun install
      - name: Build web assets
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          go run build.go web-build
      - uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: web/dist
      - name: Go tools
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go go-install
          go generate ./web
          go generate ./pkg/plugin/plugin.go
      - name: Build binary
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go build
          ./build/octant version
      - name: Build electron binary
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go build-electron
      - name: Build Electron (macOS)
        if: matrix.platform == 'macos-latest' && startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          cd web
          bun run build-electron
          bun electron-builder --mac -p never
      - name: Build Electron (Linux)
        if: matrix.platform == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          cd web
          bun run build-electron
          bun electron-builder --linux -p never
      - uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: electron-artifacts-${{ matrix.platform }}
          path: web/release/Octant*

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [bundle_assets, verify_tag]
    runs-on: ubuntu-latest
    container: goreleaser/goreleaser:v1.0.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: bundle
          path: web/dist
      - name: Run GoReleaser
        run: |
          goreleaser --skip-publish
      - uses: actions/upload-artifact@v4
        with:
          name: binary-artifacts
          path: dist

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [goreleaser, bundle_assets]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: binary-artifacts
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: electron-artifacts-ubuntu-latest
          path: web/release/linux
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: electron-artifacts-macos-latest
          path: web/release/mac
        continue-on-error: true
      - name: Create release
        # actions/upload-release-asset@v1 does not support glob
        run: |
          set -x
          assets=()
          for asset in ./dist/*; do
            if [[ $asset == *.txt ]] || [[ $asset == *.tar.gz ]] || [[ $asset == *.rpm ]] || [[ $asset == *.deb ]] || [[ $asset == *.zip ]]
              then
                assets+=("-a" "$asset")
            fi
          done
          for asset in ./web/release/**/Octant*; do
            shasum -a 256 "$asset" | awk '{sub(/.*\//," ",$2)} 1' >> ./dist/checksums.txt
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "${GITHUB_REF:10}" "${GITHUB_REF:10}" --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
